export default {
    'CLEAR_VIEW_SERIES':'CLEAR_VIEW_SERIES',
    'LOAD_FEATURED': 'LOAD_FEATURED',
    'LOAD_VIEW_SERIES': 'LOAD_VIEW_SERIES',
    'SET_SEARCH_PARAMS': 'SET_SEARCH_PARAMS',
    'SET_SERIES_API': 'SET_SERIES_API',
};
