export default {
    'CLEAR_DATE': 'CLEAR_DATE',
    'CLEAR_VIEW_SERIES':'CLEAR_VIEW_SERIES',
    'LOAD_DATE': 'LOAD_DATE',
    'LOAD_FEATURED': 'LOAD_FEATURED',
    'LOAD_VIEW_SERIES': 'LOAD_VIEW_SERIES',
    'SET_SEARCH_PARAMS': 'SET_SEARCH_PARAMS',
    'SET_SERIES_API': 'SET_SERIES_API',
    'SET_SERIE_TAGS': 'SET_SERIE_TAGS',
    'SET_UNIT_FORMAT': 'SET_UNIT_FORMAT',
};
